name: Simple Runner Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Run-Test:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest] # windows-latest, macos-latest
    runs-on: ${{ matrix.os }}
    name: Run Test
    steps:
      - run: echo "Trigger event.. ${{ github.event_name }}. Runner OS.. ${{ runner.os }}."
      - name: Simple Runner
        uses: keysight-eggplant/eggplant-github-action@v1.0.17-beta
        with:
          serverURL: "https://uat.dai.webperfdev.com"
          testConfigID: "70cba0ed-6068-4df0-ab32-0018ed24380c" # gherkin: c07d3c07-5e02-4b74-ab49-79ea0aac67d4
          clientID: "client:dai:api:integration:a8a44ff4-c5a4-41a3-8edc-59bb8a3548da"
          clientSecret: "${{secrets.DAI_CLIENT_SECRET}}"
          # filterBy: ""
          # step_status_include
          # step_status_exclude
          # test_case_tag_include
          # test_case_tag_exclude
          # test_case_name_include
          # test_case_name_exclude
          # scenario_tag
          # filterByJson:
          # previousTaskInstanceID: